# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause

wireplumber.components = [
  {
    name = 91-pal-default-nodes.lua
    type = script/lua
  }
]
